language: python
python:
  - "3.5"
install:
  - pip install numpy matplotlib seaborn
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
  python test/run_tests.py
